# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main # The branch name your are commit the new changes

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Build and Push
#     steps:
#       - name: git-checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20.10'

#       - name: Install all dependencies
#         run: npm install

#       - name: Build
#         run: npm run build:prod # The build command of your project
#       - name: Add .htaccess
#         run: |
#           echo "RewriteEngine On" >> dist/demoghaction/browser/.htaccess
#           echo "# If an existing asset or directory is requested go to it as it is" >> dist/bangis/.htaccess
#           echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]" >> dist/bangis/.htaccess
#           echo "RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d" >> dist/bangis/.htaccess
#           echo "RewriteRule ^ - [L]" >> dist/bangis/.htaccess
#           echo "" >> dist/bangis/.htaccess
#           echo "# If the requested resource doesn't exist, use index.html" >> dist/bangis/.htaccess
#           echo "RewriteRule ^ /index.html" >> dist/demoghaction/.htaccess

#       - name: Push
#         uses: s0/git-publish-subdir-action@develop
#         env:
#           REPO: self
#           BRANCH: prod # The branch name where you want to push the assets
#           FOLDER: dist/demoghaction # The directory where your assets are generated
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
#           MESSAGE: "Build: ({sha}) {msg}" # The commit message

name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/demoghaction/browser
